### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ankush-soni** [Darshan-AS/sha3-keccak#1]
I need to write a program for SHA-3 with customised input size. (As in instead of fixing the values for Rate and Capacity, I want the user to enter the value of rate). 
I tried modifying your code, it looks as follows - 

`class Keccak:`

    __STATE_LENGTH = 1600
    __DELIMITED_SUFFIX = 0x06
    
    def __init__(self,variant):
        # __STATE_LENGTH = 1600
        # __DELIMITED_SUFFIX = 0x06
        self.__state_bytes_length = self.__STATE_LENGTH // 8
        self.__delimited_suffix = self.__DELIMITED_SUFFIX
        self.__SHA3_RATE_LENGTH = variant
        __SHA3_CAPACITY_LENGTH = self.__STATE_LENGTH - self.__SHA3_RATE_LENGTH
        self.__SHA3_HASH_LENGTH = __SHA3_CAPACITY_LENGTH/2
        self.__rate_bytes_length = self.__SHA3_RATE_LENGTH
        self.__hash_bytes_length = self.__SHA3_HASH_LENGTH // 8`

Rest everything remains the same.

The Main.py is as follows - 
```

variant = int(input("Enter the rate value of SHA3: \n"))
keccak = None
try:
    keccak = Keccak(variant)
except ValueError as v:
    print(v)
    exit(0)
file_name = input("Enter a file name: ")
file = open(file_name, "rb")
contents = file.read()
print("Hash:" + str(original_hash)[2:-1] + "\nLength of Hash: " + str(len(original_hash)))
```

However, this gives me the following error - 
```
IndexError                                Traceback (most recent call last)

<ipython-input-3-32f81b3fef9e> in <module>()
     14 contents = file.read()
     15 start = time.time()
---> 16 original_hash = keccak.get_hash_of(contents)
     17 end = time.time()
     18 file.close()

<ipython-input-1-ef55558609f7> in get_hash_of(self, input_bytes)
    125 
    126             for i in range(block_size):
--> 127                 self.__state_in_bytes[i] ^= input_bytes[message_offset + i]
    128 
    129             message_offset += block_size

IndexError: bytearray index out of range
```
I am unable to figure out why this is happening. Can you help?

**Comment by Darshan-AS** [comment]
Hi, I suspect the index out of bound in the snippet above could be due to the fact that `__rate_bytes_length` is set to bit length rather than byte length.

Try changing it to:
```
self.__rate_bytes_length = self.__SHA3_RATE_LENGTH // 8
```

P. S, now that I look back at the code I wrote as an undergrad, I can see a bunch of ways it can be improved. Including customising the variant. Thanks for bringing it up!

**Comment by ankush-soni** [comment]
Hi Darshan,
The code worked using the fix that you gave in the comment. Thank you for that. :)
However, after modifying the rate and capacity bits, there's a problem with the output received.

The output(512 bit hash for SHA3-512) for the same file is coming out to be different in both the cases. As in when I execute your code on a file named X, it gives a particular hash H(X). But when I execute my modified code with the rate value as 576 (which is the same as for SHA3-512), the output comes out to be H'(X) that should have been H(X) instead.

Can you help me figure out the problem?
This is the output from your code:
![SHA3_Github](https://user-images.githubusercontent.com/19350966/148052615-302c8576-c3b2-43ba-8e08-d8da2f239196.png)



This is the output from my code:
![SHA3_Modified](https://user-images.githubusercontent.com/19350966/148052620-780842c8-3576-43f1-a6e5-1f9936c68879.png)

You can see that I am using the same file for both.
